# Alternative GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  Hyperion_Core_config = debug
  GLFW_config = debug
  ImGui_config = debug
  Glad_config = debug
  Tracy_config = debug
  Hyperion_Editor_config = debug
  Hyperion_Sandbox_config = debug

else ifeq ($(config),release)
  Hyperion_Core_config = release
  GLFW_config = release
  ImGui_config = release
  Glad_config = release
  Tracy_config = release
  Hyperion_Editor_config = release
  Hyperion_Sandbox_config = release

else
  $(error "invalid configuration $(config)")
endif

PROJECTS := Hyperion-Core GLFW ImGui Glad Tracy Hyperion-Editor Hyperion-Sandbox

.PHONY: all clean help $(PROJECTS) Core Dependecies

all: $(PROJECTS)

Core: Hyperion-Core

Dependecies: GLFW Glad ImGui Tracy

Hyperion-Core: GLFW Glad ImGui Tracy
ifneq (,$(Hyperion_Core_config))
	@echo "==== Building Hyperion-Core ($(Hyperion_Core_config)) ===="
	@${MAKE} --no-print-directory -C Engine/Hyperion-Core -f Makefile config=$(Hyperion_Core_config)
endif

GLFW:
ifneq (,$(GLFW_config))
	@echo "==== Building GLFW ($(GLFW_config)) ===="
	@${MAKE} --no-print-directory -C Engine/Hyperion-Core/External/GLFW -f Makefile config=$(GLFW_config)
endif

ImGui:
ifneq (,$(ImGui_config))
	@echo "==== Building ImGui ($(ImGui_config)) ===="
	@${MAKE} --no-print-directory -C Engine/Hyperion-Core/External/ImGui -f Makefile config=$(ImGui_config)
endif

Glad:
ifneq (,$(Glad_config))
	@echo "==== Building Glad ($(Glad_config)) ===="
	@${MAKE} --no-print-directory -C Engine/Hyperion-Core/External/Glad -f Makefile config=$(Glad_config)
endif

Tracy:
ifneq (,$(Tracy_config))
	@echo "==== Building Tracy ($(Tracy_config)) ===="
	@${MAKE} --no-print-directory -C Engine/Hyperion-Core/External/Tracy -f Makefile config=$(Tracy_config)
endif

Hyperion-Editor: Hyperion-Core
ifneq (,$(Hyperion_Editor_config))
	@echo "==== Building Hyperion-Editor ($(Hyperion_Editor_config)) ===="
	@${MAKE} --no-print-directory -C Engine/Hyperion-Editor -f Makefile config=$(Hyperion_Editor_config)
endif

Hyperion-Sandbox: Hyperion-Core
ifneq (,$(Hyperion_Sandbox_config))
	@echo "==== Building Hyperion-Sandbox ($(Hyperion_Sandbox_config)) ===="
	@${MAKE} --no-print-directory -C Engine/Hyperion-Sandbox -f Makefile config=$(Hyperion_Sandbox_config)
endif

clean:
	@${MAKE} --no-print-directory -C Engine/Hyperion-Core -f Makefile clean
	@${MAKE} --no-print-directory -C Engine/Hyperion-Core/External/GLFW -f Makefile clean
	@${MAKE} --no-print-directory -C Engine/Hyperion-Core/External/ImGui -f Makefile clean
	@${MAKE} --no-print-directory -C Engine/Hyperion-Core/External/Glad -f Makefile clean
	@${MAKE} --no-print-directory -C Engine/Hyperion-Core/External/Tracy -f Makefile clean
	@${MAKE} --no-print-directory -C Engine/Hyperion-Editor -f Makefile clean
	@${MAKE} --no-print-directory -C Engine/Hyperion-Sandbox -f Makefile clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo "  release"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   Hyperion-Core"
	@echo "   GLFW"
	@echo "   ImGui"
	@echo "   Glad"
	@echo "   Tracy"
	@echo "   Hyperion-Editor"
	@echo "   Hyperion-Sandbox"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"